analyzer:
  compound-path: dictionary.dic
  compound-classpath: classpath:dictionary.dic
  synonyms-path: synonym.dic
  synonyms-classpath: classpath:synonym.dic
logging:
  level:
    io.legendcup: DEBUG
    org.springframework: INFO
    org.springframework.data.elasticsearch.client.WIRE: TRACE
